---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: grails.plugin.gwt.requestfactory
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'